export const roleList = {
  superAdmin: {
    routes: [
      '/alarm-center',
      '/record',
      '/system-layout',
      '/system-layout/system-maintenance',
      '/system-layout/equipment-management',
      '/system-layout/ai-service',
      '/system-layout/system-maintenance/system-maintenance',
      '/system-layout/system-maintenance/account-management',
      '/system-layout/system-maintenance/push-configuration',
      '/system-layout/system-maintenance/system-journal',
      '/system-layout/system-maintenance/network-configuration',
      '/system-layout/system-maintenance/performance-monitor',
      '/system-layout/system-maintenance/platform-access',
    ],
    permission: [
      'alarm-center-look',
      'alarm-center-click',
      'record-look',
      'record-search',
      'record-select',
      'equipment-management-look',
      'equipment-management-search',
      'equipment-management-scene-add',
      'equipment-management-scene-edit',
      'equipment-management-scene-delete',
      'equipment-management-equipment-add',
      'equipment-management-equipment-edit',
      'equipment-management-equipment-delete',
      'equipment-management-equipment-detail',
      'equipment-management-ai-look',
      'equipment-management-ai-edit',
      'ai-service-look',
      'ai-service-add',
      'ai-service-switch',
      'ai-service-edit',
      'system-maintenance-look',
      'system-maintenance-edit-logo',
      'system-maintenance-edit-name',
      'system-maintenance-edit-time',
      'system-maintenance-firmware-update',
      'system-maintenance-software-update',
      'system-maintenance-shutdown',
      'system-maintenance-factory-data-reset',
      'system-maintenance-account-number-look',
      'system-maintenance-account-number-add',
      'system-maintenance-account-number-edit',
      'system-maintenance-account-number-reset',
      'system-maintenance-account-number-delete',
      'system-maintenance-push-add',
      'system-maintenance-push-edit',
      'system-maintenance-push-delete',
      'system-maintenance-network-edit',
      'system-maintenance-log-search',
      'system-maintenance-log-reset',
      'system-maintenance-log-export',
      'system-maintenance-perf-mon-look',
      'local-detection-delete',
      'local-detection-task-handle',
      'local-detection-detail-export',
    ],
  },
}

import { isAuth } from '@/config'

export interface Menu {
  name: string
  path: string
  icon?: string | null
  menuType?: number
  sort?: number
  auth: boolean
  children?: Menu[]
}

// 是否权限控制（开发环境权限放开，生产环境开启）
export const menuList: Menu[] = [
  {
    name: '报警中心',
    path: '/alarm-center',
    icon: null,
    menuType: 0,
    sort: 1,
    auth: isAuth,
  },
  {
    name: '记录查询',
    path: '/record',
    icon: null,
    menuType: 0,
    sort: 1,
    auth: isAuth,
  },
  {
    name: '配置管理',
    path: '/system-layout',
    icon: null,
    menuType: 0,
    sort: 1,
    auth: isAuth,
    children: [
      {
        name: '摄像头管理',
        path: '/system-layout/equipment-management',
        icon: 'icon-shexiangtou',
        menuType: 0,
        sort: 1,
        auth: isAuth,
      },
      {
        name: 'AI服务',
        path: '/system-layout/ai-service',
        icon: 'icon-moban',
        menuType: 0,
        sort: 1,
        auth: isAuth,
      },
      {
        name: '系统维护',
        path: '/system-layout/system-maintenance',
        icon: 'icon-chilun',
        menuType: 0,
        sort: 1,
        auth: isAuth,
        children: [
          {
            name: '通用配置',
            path: '/system-layout/system-maintenance/system-maintenance',
            icon: null,
            menuType: 0,
            sort: 1,
            auth: isAuth,
          },
          {
            name: '账号管理',
            path: '/system-layout/system-maintenance/account-management',
            icon: null,
            menuType: 0,
            sort: 1,
            auth: isAuth,
          },
          {
            name: '算法授权',
            path: '/system-layout/system-maintenance/algo-auth',
            icon: null,
            menuType: 0,
            sort: 1,
            auth: isAuth,
          },
          {
            name: '推送配置',
            path: '/system-layout/system-maintenance/push-configuration',
            icon: null,
            menuType: 0,
            sort: 1,
            auth: isAuth,
          },
          {
            name: '平台接入',
            path: '/system-layout/system-maintenance/platform-access',
            icon: null,
            menuType: 0,
            sort: 1,
            auth: isAuth,
          },
          {
            name: 'NVR配置',
            path: '/system-layout/system-maintenance/nvr-configuration',
            icon: null,
            menuType: 0,
            sort: 1,
            auth: isAuth,
          },
          {
            name: '网络配置',
            path: '/system-layout/system-maintenance/network-configuration',
            icon: null,
            menuType: 0,
            sort: 1,
            auth: isAuth,
          },
          {
            name: '系统日志',
            path: '/system-layout/system-maintenance/system-journal',
            icon: null,
            menuType: 0,
            sort: 1,
            auth: isAuth,
          },
          {
            name: '性能监控',
            path: '/system-layout/system-maintenance/performance-monitor',
            icon: null,
            menuType: 0,
            sort: 1,
            auth: isAuth,
          },
        ],
      },
      {
        name: '本地数据检测',
        path: '/system-layout/local-detection',
        icon: 'icon-saomiao',
        menuType: 0,
        sort: 1,
        auth: isAuth,
        // children: [
        //   {
        //     name: '本地检测',
        //     path: '/system-layout/local-detection/list',
        //     icon: 'icon-saomiao',
        //     menuType: 0,
        //     sort: 1,
        //     auth: isAuth,
        //   },
        //   {
        //     name: '本地检测',
        //     path: '/system-layout/local-detection/form',
        //     icon: 'icon-saomiao',
        //     menuType: 0,
        //     sort: 1,
        //     auth: isAuth,
        //   },
        // ],
      },
    ],
  },
]
